name: CCraft
main: plugin.main.CCraft
version: 1.0
commands:
  worker:
    description: Spawns a worker
    usage: /<command> create [workertype][name]
  worker:
    description: Gets the job of the selected worker
    usage: /<command> job
  worker:
    description: Gets the job of the selected worker
    usage: /<command> find [material][threshold]
  cctest:
      description: moves an npc to the player
      usage: /<command> moveto me
  cctest:
      description: moves an npc to the player with given speed
      usage: /<command> moveto me [speed]   
  cctest:
      description: moves an npc to the player with given speed
      usage: /<command> make [jobname]  
    
